### ISSUE TITLE
Version locked with moneyphp/money

### ISSUE THREAD

**Issue by lloricode** [andriichuk/laracash#11]
Hi @andriichuk 

just a question, why do we need to a fix version?

https://github.com/andriichuk/laracash/blob/15302fbbc73dfd6a55d0dce35531cfaefc1609fc/composer.json#L25

we can use just like this so we able to get update in case
```json
"moneyphp/money": "^3.3.1" 
```

Thank you

**Comment by andriichuk** [comment]
Hi @lloricode! Once I got an error while updating the patch version. But I think we can revert the version locking here.
Thank you!

**Comment by andriichuk** [comment]
@lloricode Reverted version and removed composer.lock file from repo
https://github.com/andriichuk/laracash/commit/aa60f95e191d51774257b1a8c8e4f8dd564a676c
