### ISSUE TITLE
Laravel 9 & NULL cast

### ISSUE THREAD

**Issue by stefandoorn** [andriichuk/laracash#17]
I think the `MoneyCast` class is not compatible with this Laravel 9 change: https://laravel.com/docs/9.x/upgrade#custom-casts-and-null. I don't know enough of the internals unfortunately to provide a PR at the moment.

**Comment by stefandoorn** [comment]
Adding this to my local `set` and `get` does fix it for my test suite, but I'm not sure if this is a proper fix. It implies a BC on the return types..

```php
if (null === $value) {
    return null;
}
```

**Comment by andriichuk** [comment]
Hi @stefandoorn! Thank you for your attention. I will merge the fix later today.
