### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by stefandoorn** [andriichuk/laracash#21]
Hi @andriichuk - would you be able to add Laravel 11 support?

Laravel Shift already provided a PR (https://github.com/andriichuk/laracash/pull/20) and it seems to pass CI.

Thanks!

**Comment by andriichuk** [comment]
Hi! Merged the request, please check the changes in the version v2.2.0.

**Comment by stefandoorn** [comment]
Thanks!
