### ISSUE TITLE
Facade not found

### ISSUE THREAD

**Issue by juliomotol** [andriichuk/laracash#7]
Everytime we try to access via facade, this happens

![image](https://user-images.githubusercontent.com/21353103/95181508-fa245880-07f5-11eb-885a-981e16c60bbf.png)

The class name for aliasing the the `composer.json` doesn't match the namespace of the facade.

https://github.com/andriichuk/laracash/blob/52e9f934c28297ed47c9ca7366f0690448be57b7/src/Facades/Laracash.php#L5
https://github.com/andriichuk/laracash/blob/52e9f934c28297ed47c9ca7366f0690448be57b7/composer.json#L53

Will open a PR later in the day.

**Comment by andriichuk** [comment]
@juliomotol Thank you
