### ISSUE TITLE
Get currency from related model

### ISSUE THREAD

**Issue by juliomotol** [andriichuk/laracash#9]
Given the following:

### Database Schema

```
orders
    - id
    - total_price
    - currency

order_items
    - id
    - order_id
    - product_id
    - unit_price
    - quantity
```
### Order Model

```
class Order extends Model implements HasMoneyWithCurrencyInterface
{
    use HasMoneyWithCurrency;
    use HasCurrency;

    protected $casts = [
        'total_price' => MoneyCast::class,
        'currency' => CurrencyCast::class,
    ];

    public function getCurrencyColumnFor(string $field): string
    {
        return 'currency';
    }

    public function items()
    {
        return $this->hasMany(OrderItems::class);
    }
}
```
### OrderItem Model
```
class OrderItem extends Model implements HasMoneyWithCurrencyInterface
{
    use HasMoneyWithCurrency;
    use HasCurrency;

    protected $casts = [
        'unit_price' => MoneyCast::class,
    ];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
}
```

It would be nice if I could reference the `currency` of `Order` as the currency for `unit_price` in `OrderItems`.

**Comment by andriichuk** [comment]
Hi @juliomotol!
Try to use `getDefaultCurrencyFor` method implementation from `HasCurrencyInterface` contract

```php
class OrderItem extends Model implements HasMoneyWithCurrencyInterface, HasCurrencyInterface
{
    use HasMoneyWithCurrency;
    use HasCurrency;

    protected $casts = [
        'unit_price' => MoneyCast::class,
    ];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
    
    public function getDefaultCurrencyFor(string $field): Currency
    {
        return $this->order->currency;
    }
}
```

**Comment by juliomotol** [comment]
Thanks! `getDefaultCurrencyFor()` works! It might be handy to add this in the docs for orders to know.

**Comment by juliomotol** [comment]
I'd like to add in this note that when doing this

```
$order = Order::create([...]);

$order->items()->create([
    'product_id' => '1',
    'unit_price' => '10000',
    'quantity' => '1'
]);
```

The following errors happened:

### Order Relation is not yet ready.

During creation, it tried to set the cast for `unit_price` with its currency as `$this->order->currency`. But the relation is not yet ready. so it threw an `Trying to get property 'currency' of non-object`.

I worked around this by coalescing to `$this->getDefaultCurrency()`

```
public function getDefaultCurrencyFor(string $field): Currency
{
    return $this->order->currency ?? $this->getDefaultCurrency();
}
```

### Tried to saving to `currency` column

After the work around it proceeded to actually running the sql query. but it tried to save to a `currency` column. But that column is not defined in the schema thus throwing this error

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'currency' in 'field list' (SQL: insert into `order_items` (`product_id`, `quantity`, `unit_price`, `currency`, `order_id`, `updated_at`, `created_at`) values (1, 1, 10000, PHP, 1, 2020-10-09 17:53:24, 2020-10-09 17:53:24))
```

I then looked deep into the `MoneyCast` class

https://github.com/andriichuk/laracash/blob/c7ef4356f0fc9ddce1388fe078e1dec900b7db80/src/Casts/MoneyCast.php#L53-L58

Now knowing this snippet, I then tried to remove the `HasMoneyWithCurrencyInterface` for the model and it proceeded as intended.

But here is the **kicker**, removing the `HasMoneyWithCurrencyInterface` will ~~breaks the cast entirely~~ fallback to the `currency` defined in the config instead of using the currency from the related model.

https://github.com/andriichuk/laracash/blob/c7ef4356f0fc9ddce1388fe078e1dec900b7db80/src/Casts/MoneyCast.php#L63-L67

**Comment by andriichuk** [comment]
Hi @juliomotol!
Sorry for late response. Thanks for PR!
